headers: Fix IDirectXVideoDecoderService declaration in dxva2api.idl
This matches the declaration with official documentation and fixes
the following two compiler errors in apitrace project.

d3d9trace.cpp:28469:59: error: invalid conversion from 'const DXVA2_ConfigPictureDecode*' to 'DXVA2_ConfigPictureDecode*' [-fpermissive]
d3d9trace.cpp:28194:65: error: invalid conversion from 'void*' to 'IUnknown*' [-fpermissive]

Wine commit 467604c6613e7a41201e0af34f009700bc8ac392
Previous mingw-w64 commit 2c60d6c47d6f6623b32d87e92a413ccebf5b96e6

Signed-off-by: Biswapriyo Nath <nathbappai@gmail.com>
Signed-off-by: LIU Hao <lh_mouse@126.com>