headers/wincon: Don't define `LF_FACESIZE` when `NOGDI` is in effect
Defining it prevents other definitions such as `LOGFONT{A,W}` and causes
errors:

  $ echo '#include <shobjidl.h>' | gcc -xc -c -DNOGDI -
  In file included from <stdin>:1:
  C:/msys32/mingw32/i686-w64-mingw32/include/shobjidl.h:7170:15: error:
  unknown type name 'LOGFONTW'
   7170 |         const LOGFONTW *plf);
        |               ^~~~~~~~
  C:/msys32/mingw32/i686-w64-mingw32/include/shobjidl.h:7324:15: error:
  unknown type name 'LOGFONTW'
   7324 |         const LOGFONTW *plf,
        |               ^~~~~~~~
  C:/msys32/mingw32/i686-w64-mingw32/include/shobjidl.h:7329:9: error:
  unknown type name 'LOGFONTW'; did you mean 'LPFONT'?
   7329 |         LOGFONTW *plf);
        |         ^~~~~~~~
        |         LPFONT

Reference: https://sourceforge.net/p/mingw-w64/mailman/message/37288840/
Reported-by: Orgad Shaneh <orgads@gmail.com>
Signed-off-by: Liu Hao <lh_mouse@126.com>